### ISSUE TITLE
FEAT: Finish event logic

### ISSUE THREAD

**Issue by enzo-garofalo** [enzo-garofalo/PI2--Time-1#49]
implementar a lógica do finish event
mudar o modal, para colocar os parametros,
lembra o id do evento já está no modal
colher o veredito (se aconteceu ou não)

integrar com o back end (chamar a rota e finalizar evento)

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added logic to finish an event, including updating the modal to collect the verdict and integrating with the backend to finalize the event.

You can review changes in this commit: https://github.com/mnmnk43434/enzo-garofalo-PI2--Time-1-49/commit/ea3df18d2cdeb18962c3dba0cc8521c59c89e9e0.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
